---
packages:
  ard_common: !include esphome_ard_common.yaml
  basic_package: !include ../nspanel_esphome.yaml  # Basic package
  cover_package: !include ../esphome/nspanel_esphome_addon_cover.yaml
...
