---
packages:
  common: !include esphome_idf_common.yaml
  basic_package: !include ../nspanel_esphome.yaml  # Core package
  addon_ble_tracker: !include ../esphome/nspanel_esphome_addon_ble_tracker.yaml
...
