---
packages:
  common: !include esphome_idf_common.yaml
  basic_package: !include ../nspanel_esphome.yaml  # Core package
  addon_bluetooth_proxy: !include ../esphome/nspanel_esphome_addon_bluetooth_proxy.yaml
...
