---
packages:
  idf_common: !include esphome_idf_common.yaml
  basic_package: !include ../nspanel_esphome.yaml  # Core package
  addon_climate_heat: !include ../esphome/nspanel_esphome_addon_climate_heat.yaml
  # addon_climate_cold: !include ../esphome/nspanel_esphome_addon_climate_cold.yaml
  # addon_climate_dual: !include ../esphome/nspanel_esphome_addon_climate_dual.yaml
  customizations: !include esphome_common_customizations.yaml
...
