---
packages:
  ard_common: !include esphome_ard_common.yaml
  basic_package: !include ../nspanel_esphome.yaml  # Core package
  addon_climate_dual: !include ../esphome/nspanel_esphome_addon_climate_dual.yaml
...
