---
packages:
  ard_common: !include esphome_ard_common.yaml
  basic_package: !include ../nspanel_esphome.yaml  # Core package
  addon_climate_heat: !include ../esphome/nspanel_esphome_addon_climate_heat.yaml
  customizations: !include esphome_common_customizations.yaml
...
