##### Sensor ######
sensor:

  - platform: template
    sensors:
      wochentag:
        friendly_name: "Wochentag"
        unique_id: 6ac64850-8563-456c-b562-92343dd96f0b
        value_template: >
          {% set days = ['Montag,', 'Dienstag,', 'Mittwoch,', 'Donnerstag,', 'Freitag,', 'Samstag,', 'Sonntag,'] %}
          {{ now().timestamp() | timestamp_custom(days[now().weekday()] ~ '  %d.%m')}}
        icon_template: mdi:calendar-range

  - platform: template
    sensors:
      wochentag01:
        friendly_name: "Wochentag+1"
        unique_id: 6b2aad54-3eb0-48cc-ae32-ee3574197f1b
        value_template: >
          {% set days = ['Montag,', 'Dienstag,', 'Mittwoch,', 'Donnerstag,', 'Freitag,', 'Samstag,', 'Sonntag,', 'Montag,'] %}
          {{(as_timestamp(now())+ (86400)) | timestamp_custom(days[now().weekday()+1] ~ '  %d.%m') }}
        icon_template: mdi:calendar-range

  - platform: template
    sensors:
      wochentag02:
        friendly_name: "Wochentag+2"
        unique_id: edbddaf0-2791-4774-b8d4-aa706f75cc7a
        value_template: >
          {% set days = ['Montag,', 'Dienstag,', 'Mittwoch,', 'Donnerstag,', 'Freitag,', 'Samstag,', 'Sonntag,', 'Montag,', 'Dienstag,'] %}
          {{(as_timestamp(now())+ (172800)) | timestamp_custom(days[now().weekday()+2] ~ '  %d.%m') }}
        icon_template: mdi:calendar-range

  - platform: template
    sensors:
      wochentag03:
        friendly_name: "Wochentag+3"
        unique_id: ad592622-db86-40f7-9961-4c1ffd21c711
        value_template: >
          {% set days = ['Montag,', 'Dienstag,', 'Mittwoch,', 'Donnerstag,', 'Freitag,', 'Samstag,', 'Sonntag,', 'Montag,', 'Dienstag,', 'Mittwoch,'] %}
          {{(as_timestamp(now())+ (259200)) | timestamp_custom(days[now().weekday()+3] ~ '  %d.%m') }}
        icon_template: mdi:calendar-range

  - platform: template
    sensors:
      wochentag04:
        friendly_name: "Wochentag+4"
        unique_id: dcb3ed45-2b89-4672-a04f-a55f025ac745
        value_template: >
          {% set days = ['Montag,', 'Dienstag,', 'Mittwoch,', 'Donnerstag,', 'Freitag,', 'Samstag,', 'Sonntag,', 'Montag,', 'Dienstag,', 'Mittwoch,', 'Donnerstag,'] %}
          {{(as_timestamp(now())+ (345600)) | timestamp_custom(days[now().weekday()+4] ~ '  %d.%m') }}
        icon_template: mdi:calendar-range

  - platform: template
    sensors:
      wochentag05:
        friendly_name: "Wochentag+5"
        unique_id: 77e642a5-de54-452d-9f4a-febe3a7851c2
        value_template: >
          {% set days = ['Montag,', 'Dienstag,', 'Mittwoch,', 'Donnerstag,', 'Freitag,', 'Samstag,', 'Sonntag,', 'Montag,', 'Dienstag,', 'Mittwoch,', 'Donnerstag,', 'Freitag,'] %}
          {{(as_timestamp(now())+ (432000)) | timestamp_custom(days[now().weekday()+ 5] ~ '  %d.%m') }}
        icon_template: mdi:calendar-range

###### NSPanel Büro - climate target temperature #####
  - platform: template
    sensors:
      nspanel_buro_target_temp:
        unique_id: 2393ab74-21ce-42d3-b15e-ec162b9d6f31
        friendly_name: NSPanel Buro Target Temp
        value_template: "{{ state_attr('climate.nspanel_buro', 'temperature') }}"

###### NSPanel Büro - climate target temperature #####
  - platform: template
    sensors:
      nspanel_lea_target_temp:
        unique_id: e8e61ff7-3a41-47ad-bd6c-303f730de96f
        friendly_name: NSPanel Lea Target Temp
        value_template: "{{ state_attr('climate.nspanel_lea', 'temperature') }}"
