#####################################################################################################
##### NSPANEL ESPHOME created by Blackymas - https://github.com/Blackymas/NSPanel_HA_Blueprint  #####
##### ESPHOME CORE - PAGE - QRCODE                                                              #####
##### PLEASE only make changes if it is necessary and also the required knowledge is available. #####
##### For normal use with the Blueprint, no changes are necessary.                              #####
#####################################################################################################

---
substitutions:
  PAGE_QRCODE_ID: 17

api:
  actions:
    # Dynamically displays QR codes on the ESPHome UI for sharing information such as WiFi passwords or website links.
    - action: qrcode
      variables:
        title: string   # Heading or title for the QR code, offering context or instructions.
        qrcode: string  # Data or URL to be encoded into the QR code.
        show: bool      # Flag to immediately display the QR code page upon service invocation.
      then:
        - lambda: |-
            if (current_page_id == ${PAGE_HOME_ID})
              disp1->send_command_printf("vis bt_qrcode,%i", qrcode.empty() ? 0 : 1);
            disp1->set_component_text("qrcode.qrcode_label", title.c_str());
            disp1->set_component_text("qrcode.qrcode_value", qrcode.c_str());
            if (show)
              goto_page->execute(${PAGE_QRCODE_ID});

            // Update blueprint status
            blueprint_status_flags.qrcode = true;

script:
  - id: !extend boot
    then:
      - lambda: |-
          disp1->set_component_font("home.bt_qrcode", id(home_custom_buttons_font_id));

  - id: !extend page_change
    then:
      - lambda: if (new_page_id == ${PAGE_QRCODE_ID}) page_qrcode->execute();

  - id: page_qrcode
    mode: single
    then:  # There's nothing here so far

  - id: !extend stop_page_constructors
    then:
      - lambda: page_qrcode->stop();
...
