#####################################################################################################
##### NSPANEL ESPHOME created by Blackymas - https://github.com/Blackymas/NSPanel_HA_Blueprint  #####
##### ESPHOME CORE - HARDWARE - BUZZER                                                          #####
##### PLEASE only make changes if it is necessary and also the required knowledge is available. #####
##### For normal use with the Blueprint, no changes are necessary.                              #####
#####################################################################################################

##### External references #####
# nspanel_esphome_core.yaml:
#   api.actions.notification_show
###############################

---
substitutions:
  BOOT_STEP_HW_WIFI: '9'
  MDI_ICON_API_OFF: "\uF256"         # mdi:api-off
  MDI_ICON_HOME_ASSISTANT: "\uE7CF"  # mdi:home-assistant
  MDI_ICON_RESTART: "\uE708"         # mdi:restart
  MDI_ICON_WIFI: "\uE5A8"            # mdi:wifi
  MDI_ICON_WIFI_OFF: "\uE5A9"        # mdi:wifi-off
  TAG_CORE_HW_WIFI: core_hw_wifi

api:
  on_client_connected:
    then:
      - script.execute: refresh_wifi_icon
  on_client_disconnected:
    then:
      - script.execute: refresh_wifi_icon

esphome:
  platformio_options:
    build_flags:
      - -D NSPANEL_HA_BLUEPRINT_CORE_HW_WIFI
  on_boot:
    - priority: 600.9  # This is where most sensors are set up.
      then:
        - lambda: |-
            nspanel_ha_blueprint::set_device_name("${name}");

  on_shutdown:
    - priority: 0.9
      then:  # Update Wi-Fi icon
        - lambda: |-
            set_component_text->execute(${PAGE_ID_HOME}, "wifi_icon", "${MDI_ICON_RESTART}");
            set_component_font_color->execute(${PAGE_ID_HOME}, "wifi_icon", 63488);

script:
  - id: !extend boot_package_register
    then:
      - lambda: boot_package_register_add->execute(${BOOT_STEP_HW_WIFI}, "HW_WIFI", "HW Wi-Fi");

  - id: !extend dump_config
    then:
      - lambda: |-
          if (wifi_component->is_connected()) {
            float rssi = wifi_rssi->state;
            const char *rssi_status = "Unknown"; // Use const char* to avoid dynamic memory allocation
            if (rssi > -50) rssi_status = "Excellent";
            else if (rssi > -60) rssi_status = "Good";
            else if (rssi > -70) rssi_status = "Fair";
            else if (rssi > -80) rssi_status = "Weak";
            else rssi_status = "Poor";
            if (rssi > -70) ESP_LOGI("${TAG_CORE_HW_WIFI}", "Wi-Fi:         %s (%.0f dBm)", rssi_status, rssi);
            else if (rssi > -80) ESP_LOGW("${TAG_CORE_HW_WIFI}", "Wi-Fi:         %s (%.0f dBm)", rssi_status, rssi);
            else ESP_LOGE("${TAG_CORE_HW_WIFI}", "Wi-Fi:         %s (%.0f dBm)", rssi_status, rssi);
          } else {
            ESP_LOGE("${TAG_CORE_HW_WIFI}", "Wi-Fi:         DISCONNECTED");
          }
          ESP_LOGI("${TAG_CORE_HW_WIFI}", "Device name:   %s", nspanel_ha_blueprint::get_device_name());

  - id: !extend page_boot
    then:
      - script.execute: page_boot_wifi

  - id: page_boot_wifi
    mode: restart
    then:
      - lambda: |-
          if (!wifi_component->is_connected())
            page_boot_log->execute("Boot", "Waiting for Wi-Fi");
      - wait_until:
          condition:
            - lambda: return wifi_component->is_connected();
            - lambda: return current_page_id == ${PAGE_ID_BOOT};
          timeout: 20s
      - lambda: |-
          if (current_page_id == ${PAGE_ID_BOOT})
            disp1->set_component_text_printf("sys_ip", "IP: %s", network::get_ip_addresses()[0].str().c_str());

  - id: !extend page_home
    then:
      - script.execute: refresh_wifi_icon

  - id: refresh_wifi_icon
    mode: restart
    then:
      - lambda: |-
          ESP_LOGV("${TAG_CORE_HW_WIFI}", "Refreshing Wi-Fi icon");
          static DisplayComponent* wifi_icon = get_component(${PAGE_ID_HOME}, "wifi_icon");
          static bool blueprint_is_connected = false;
          static bool api_is_connected = false;
          static bool wifi_is_connected = false;
          static bool wifi_rssi_warning = false;
          bool status_has_changed = blueprint_is_connected != is_boot_step_completed(${BOOT_STEP_VERSIONING}) or
                                    wifi_is_connected != wifi_component->is_connected() or
                                    api_is_connected != api_server->is_connected();
          if (status_has_changed) {
            ESP_LOGV("${TAG_CORE_HW_WIFI}", "Status has changed");
            blueprint_is_connected = is_boot_step_completed(${BOOT_STEP_VERSIONING});
            api_is_connected = api_server->is_connected();
            wifi_is_connected = wifi_component->is_connected();
            // Update Wi-Fi icon
            char new_wifi_icon[5] = "\0";  // Allocate sufficient space to store UTF-8 icon
            if (wifi_is_connected) {
                if (api_is_connected) {
                    if (blueprint_is_connected) {
                        copyStringToCharArray(new_wifi_icon, "${MDI_ICON_WIFI}");
                    } else {
                        copyStringToCharArray(new_wifi_icon, "${MDI_ICON_HOME_ASSISTANT}");
                    }
                } else {
                    copyStringToCharArray(new_wifi_icon, "${MDI_ICON_API_OFF}");
                }
            } else {
                copyStringToCharArray(new_wifi_icon, "${MDI_ICON_WIFI_OFF}");
            }

            if (new_wifi_icon[0] != '\0' and strcmp(wifi_icon->text, new_wifi_icon) != 0)
              display_component_update_text->execute(wifi_icon, new_wifi_icon);

            if (blueprint_is_connected and api_is_connected and wifi_is_connected) {
              ESP_LOGI("${TAG_CORE_HW_WIFI}", "Wi-Fi icon changed to %s (\\u%04" PRIx32 ")",
                        new_wifi_icon, decode_utf8(new_wifi_icon));
              set_variable_value->execute("api", 1);
            } else {
              ESP_LOGW("${TAG_CORE_HW_WIFI}", "Wi-Fi icon changed to %s (\\u%04" PRIx32 ")",
                        new_wifi_icon, decode_utf8(new_wifi_icon));
              set_variable_value->execute("api", 0);
            }
          }

          // Update Wi-Fi icon color
          if (status_has_changed or (wifi_rssi_warning != (wifi_rssi->state <= -70))) {
            ESP_LOGV("${TAG_CORE_HW_WIFI}", "RSSI changed");
            wifi_rssi_warning = (wifi_rssi->state <= -70);
            display_component_update_color->execute(wifi_icon,
                                                    (blueprint_is_connected and wifi_is_connected and api_is_connected)
                                                    ? (wifi_rssi_warning ? 64992 : 33808)
                                                    : 63488);
          }

  - id: !extend stop_all
    then:
      - lambda: |-
          page_boot_wifi->stop();
          refresh_wifi_icon->stop();

  - id: !extend time_watchdog  # Defined by nspanel_esphome_core_base.yaml
    then:
      - lambda: |-
          if (not wifi_component->is_connected()) {
            ESP_LOGW("${TAG_CORE_HW_WIFI}", "Retrying Wi-Fi connection");
            wifi_component->retry_connect();
          }
          refresh_wifi_icon->execute();

sensor:
  ##### Wi-Fi Signal stregth
  - name: RSSI
    id: wifi_rssi
    platform: wifi_signal
    internal: false
    disabled_by_default: false
    icon: mdi:wifi
    entity_category: diagnostic

##### WIFI SETUP #####
wifi:
  id: wifi_component
  power_save_mode: LIGHT
  networks:
    - id: wifi_default
      ssid: ${wifi_ssid}
      password: ${wifi_password}
  on_connect:
    then:
      - script.execute: refresh_wifi_icon
      - script.execute:
          id: page_boot_log
          category: Wi-Fi
          log_message: !lambda return network::get_ip_addresses()[0].str().c_str();

  on_disconnect:
    then:
      - script.execute: refresh_wifi_icon
...
