#####################################################################################################
##### NSPANEL ESPHOME created by Blackymas - https://github.com/Blackymas/NSPanel_HA_Blueprint  #####
##### ESPHOME CORE - Page Blank                                                                 #####
##### PLEASE only make changes if it is necessary and also the required knowledge is available. #####
##### For normal use with the Blueprint, no changes are necessary.                              #####
#####################################################################################################

---
substitutions:
  BOOT_STEP_PAGE_SETTINGS: '28'
  PAGE_ID_SETTINGS: '8'
  TAG_PAGE_SETTINGS: nspanel_ha_blueprint.page.settings

display:
  - id: !extend disp1
    on_touch:
      then:
        - lambda: |-
            if (page_id == 8) {  // Page Settings
              switch (component_id) {
                case 9:  // Reboot button
                  App.safe_reboot();
                  break;
              }
            }

esphome:
  platformio_options:
    build_flags:
      - -D NSPANEL_HA_BLUEPRINT_STANDARD_SETTINGS

number:
  - id: !extend display_brightness
    on_value:
      then:
        - lambda: |-
            disp1->set_component_value("settings.brightslider", int(x));
            if (current_page_id == ${PAGE_ID_SETTINGS})
              disp1->set_component_text_printf("bright_text", "%i%%", int(x));

  - id: !extend display_dim_brightness
    on_value:
      then:
        - lambda: |-
            disp1->set_component_value("settings.dimslider", int(x));
            if (current_page_id == ${PAGE_ID_SETTINGS})
              disp1->set_component_text_printf("dim_text", "%i%%", int(x));

script:
  - id: !extend boot_package_register
    then:
      - lambda: boot_package_register_add->execute(${BOOT_STEP_PAGE_SETTINGS}, "PAGE_SETTINGS", "Page Settings");

  - id: !extend boot_sequence
    then:
      - lambda: |-
          set_component_value->execute(${PAGE_ID_SETTINGS}, "dimslider",
                                        static_cast<uint8_t>(display_dim_brightness->state));
          set_component_value->execute(${PAGE_ID_SETTINGS}, "brightslider",
                                        static_cast<uint8_t>(display_brightness->state));

  - id: !extend set_var_string
    then:
      - lambda: |-
          if (component == "lbl_bright")
            display_wrapped_text->execute(${PAGE_ID_SETTINGS}, "lbl_bright", val.c_str(),
                                          id(display_mode) == 2 ? 25 : 10);
          else if (component == "lbl_dim")
            display_wrapped_text->execute(${PAGE_ID_SETTINGS}, "lbl_dim", val.c_str(),
                                          id(display_mode) == 2 ? 25 : 10);
...
