#####################################################################################################
##### NSPANEL ESPHOME created by Blackymas - https://github.com/Blackymas/NSPanel_HA_Blueprint  #####
##### ESPHome Add-on for Cover control based on time                                            #####
##### PLEASE only make changes if it is necessary and also the required knowledge is available. #####
##### For normal use with the Blueprint, no changes are necessary.                              #####
#####################################################################################################
##### ATTENTION: This will add cover elements to the core system and requires the core part.  #####
#####################################################################################################
---
substitutions:
  ### Local cover defaults ###
  interlock_wait_time: '250'
  TAG_ADDON_COVER: nspanel_ha_blueprint.addon.cover

esphome:
  platformio_options:
    build_flags:
      - -D NSPANEL_HA_BLUEPRINT_ADDON_COVER
  on_boot:
    - priority: 700.29
      then:
        - if:
            condition: &condition_NOT_safe_mode
              - lambda: return nspanel_ha_blueprint::current_panel_state != nspanel_ha_blueprint::PanelState::SAFE_MODE;
            then:
              - wait_until:
                  condition:
                    - lambda: return id(cover_interlock_wait_time).has_state();
                    - lambda: return !isnan(id(cover_interlock_wait_time).state);
              - lambda: |-
                  id(page_boot_log).execute("Cover on_boot", "Set relay interlock");
                  id(relay_1).set_interlock_wait_time(id(cover_interlock_wait_time).state);
                  id(relay_2).set_interlock_wait_time(id(cover_interlock_wait_time).state);
    - priority: 700.27
      then:
        - if:
            condition: *condition_NOT_safe_mode
            then:
              - wait_until:
                  condition:
                    - lambda: return id(cover_open_duration).has_state();
                    - lambda: return !isnan(id(cover_open_duration).state);
              - lambda: |-
                  id(page_boot_log).execute("Cover on_boot", "Set open duration");
                  id(cover_embedded).set_open_duration(id(cover_open_duration).state);
    - priority: 700.26
      then:
        - if:
            condition: *condition_NOT_safe_mode
            then:
              - wait_until:
                  condition:
                    - lambda: return id(cover_close_duration).has_state();
                    - lambda: return !isnan(id(cover_close_duration).state);
              - lambda: |-
                  id(page_boot_log).execute("Cover on_boot", "Set close duration");
                  id(cover_embedded).set_close_duration(id(cover_close_duration).state);
    - priority: 700.24
      then:
        - if:
            condition: *condition_NOT_safe_mode
            then:
              - wait_until:
                  condition:
                    - lambda: return id(cover_acceleration_wait_time).has_state();
                    - lambda: return !isnan(id(cover_acceleration_wait_time).state);
              - lambda: |-
                  id(page_boot_log).execute("Cover on_boot", "Set acc. wait time");
                  id(cover_embedded).set_acceleration_wait_time(id(cover_acceleration_wait_time).state);
    - priority: 700.23
      then:
        - if:
            condition: *condition_NOT_safe_mode
            then:
              - wait_until:
                  condition:
                    - lambda: return id(cover_direction_change_wait_time).has_state();
                    - lambda: return !isnan(id(cover_direction_change_wait_time).state);
              - lambda: |-
                  id(page_boot_log).execute("Cover on_boot", "Set dir. change wait time");
                  id(cover_embedded).set_direction_change_waittime(id(cover_direction_change_wait_time).state);
    - priority: 700.21
      then:
        - if:
            condition: *condition_NOT_safe_mode
            then:
              - wait_until:
                  condition:
                    - lambda: return id(cover_device_class).has_state();
                    - lambda: return !(id(cover_device_class).state).empty();
              - lambda: |-
                  id(page_boot_log).execute("Cover on_boot", "Set device class");
                  std::string lower_x = id(cover_device_class).state;
                  std::transform(lower_x.begin(), lower_x.end(), lower_x.begin(), ::tolower);
                  id(cover_embedded).set_device_class(lower_x.c_str());

cover:
  - id: cover_embedded
    name: Cover
    platform: feedback
    open_action:
      - switch.turn_on: cover_open_virtual_relay
    open_duration: 1ms
    close_action:
      - switch.turn_on: cover_close_virtual_relay
    close_duration: 1ms
    stop_action:
      - switch.turn_off: cover_open_virtual_relay
      - switch.turn_off: cover_close_virtual_relay
      - switch.turn_off: relay_1
      - switch.turn_off: relay_2

number:
  - id: cover_acceleration_wait_time
    name: Cover acceleration wait time
    icon: mdi:timer
    platform: template
    unit_of_measurement: ms
    internal: false
    entity_category: config
    min_value: 0
    max_value: 10000
    step: 1
    initial_value: 0
    optimistic: true
    restore_value: true
    on_value:
      - lambda: if (!isnan(x)) id(cover_embedded).set_acceleration_wait_time(x);
      - delay: 10s
      - lambda: id(cover_embedded).dump_config();
  - id: cover_direction_change_wait_time
    name: Cover direction change wait time
    icon: mdi:timer
    platform: template
    unit_of_measurement: ms
    internal: false
    entity_category: config
    min_value: 0
    max_value: 10000
    step: 1
    initial_value: 100
    optimistic: true
    restore_value: true
    on_value:
      - lambda: if (!isnan(x)) id(cover_embedded).set_direction_change_waittime(x);
      - delay: 10s
      - lambda: id(cover_embedded).dump_config();
  - id: cover_interlock_wait_time
    name: Cover interlock wait time
    icon: mdi:timer
    platform: template
    unit_of_measurement: ms
    internal: false
    entity_category: config
    min_value: 1
    max_value: 5000
    step: 1
    initial_value: ${interlock_wait_time}
    optimistic: true
    restore_value: true
    on_value:
      - lambda: |-
          if (!isnan(x)) {
            id(relay_1).set_interlock_wait_time(x);
            id(relay_2).set_interlock_wait_time(x);
          }
      - delay: 10s
      - lambda: |-
          id(relay_1).dump_config();
          id(relay_2).dump_config();
  - id: cover_open_duration
    name: Cover open duration
    icon: mdi:timer
    platform: template
    unit_of_measurement: ms
    internal: false
    entity_category: config
    min_value: 1
    max_value: 600000
    step: 1
    initial_value: 1
    optimistic: true
    restore_value: true
    on_value:
      - lambda: if (!isnan(x)) id(cover_embedded).set_open_duration(x);
      - delay: 10s
      - lambda: id(cover_embedded).dump_config();
  - id: cover_close_duration
    name: Cover close duration
    icon: mdi:timer
    platform: template
    unit_of_measurement: ms
    internal: false
    entity_category: config
    min_value: 1
    max_value: 600000
    step: 1
    initial_value: 1
    optimistic: true
    restore_value: true
    on_value:
      - lambda: if (!isnan(x)) id(cover_embedded).set_close_duration(x);
      - delay: 10s
      - lambda: id(cover_embedded).dump_config();

script:
  - id: !extend dump_config  # Defined by nspanel_esphome_core_base.yaml
    then:
      - lambda: |-
          // Check for requirements
          #if !defined(NSPANEL_HA_BLUEPRINT_STANDARD_HW_RELAYS)
            #error "The package nspanel_esphome_standard_hw_relays.yaml is required."
          #endif
          #if !defined(NSPANEL_HA_BLUEPRINT_STANDARD_PAGE_COVER)
            #error "The package nspanel_esphome_standard_page_cover.yaml is required."
          #endif
          // Check if more than one or none of the climate options are defined
          #ifdef NSPANEL_HA_BLUEPRINT_ADDON_CLIMATE_BASE
            #error "Configuration error: The add-on cover and add-on climate cannot be installed simultaneously."
          #endif
          ESP_LOGCONFIG("${TAG_ADDON_COVER}", "Add-on cover (time based):");
          id(cover_embedded).dump_config();

  - id: !extend dump_config_packages  # Defined by nspanel_esphome_core_base.yaml
    then:
      - lambda: |-
          ESP_LOGCONFIG("${TAG_ADDON_COVER}", "  - Add-on - Cover");

  - id: set_physical_relays
    mode: queued
    parameters:
      open: bool
      state: bool
    then:
      - lambda: |-
          auto cover_relays_active_index = id(cover_relays_mode).active_index();
          if (cover_relays_active_index.has_value()) {
            const bool cover_mode_std = (cover_relays_active_index.value() == 0);
            auto relay_open = (cover_mode_std) ? relay_1 : relay_2;
            auto relay_close = (cover_mode_std) ? relay_2 : relay_1;

            if (open) {
              if (state) relay_open->turn_on();
              else relay_open->turn_off();
            } else {
              if (state) relay_close->turn_on();
              else relay_close->turn_off();
            }
          } else {
            id(relay_1).turn_off();
            id(relay_2).turn_off();
          }

select:
  - id: cover_device_class
    name: Cover device class
    platform: template
    options:
      - "None"
      - "Awning"
      - "Blind"
      - "Curtain"
      - "Damper"
      - "Door"
      - "Garage"
      - "Gate"
      - "Shade"
      - "Shutter"
      - "Window"
    optimistic: true
    restore_value: true
    internal: false
    entity_category: config
    disabled_by_default: false
    icon: mdi:window-shutter-cog
    on_value:
      - lambda: |-
          if (!x.empty()) {
            std::string lower_x = x;
            std::transform(lower_x.begin(), lower_x.end(), lower_x.begin(), ::tolower);
            id(cover_embedded).set_device_class(lower_x.c_str());
          }
      - delay: 10s
      - lambda: id(cover_embedded).dump_config();

  - id: cover_relays_mode
    name: Cover relays mode
    platform: template
    options:
      - "Relay 1 opens, relay 2 closes"
      - "Relay 2 opens, relay 1 closes"
    optimistic: true
    restore_value: true
    internal: false
    entity_category: config
    disabled_by_default: false
    icon: mdi:dip-switch

switch:
  - id: !extend relay_1
    interlock: [relay_1, relay_2]
    interlock_wait_time: ${interlock_wait_time}ms
    restore_mode: ALWAYS_OFF
    internal: true
  - id: !extend relay_2
    interlock: [relay_1, relay_2]
    interlock_wait_time: ${interlock_wait_time}ms
    restore_mode: ALWAYS_OFF
    internal: true

  - id: cover_open_virtual_relay
    platform: template
    internal: true
    restore_mode: ALWAYS_OFF
    optimistic: true
    on_turn_on:
      - script.execute:
          id: set_physical_relays
          open: true
          state: true
    on_turn_off:
      - script.execute:
          id: set_physical_relays
          open: true
          state: false
  - id: cover_close_virtual_relay
    platform: template
    internal: true
    restore_mode: ALWAYS_OFF
    optimistic: true
    on_turn_on:
      - script.execute:
          id: set_physical_relays
          open: false
          state: true
    on_turn_off:
      - script.execute:
          id: set_physical_relays
          open: false
          state: false
...
