#####################################################################################################
##### NSPANEL ESPHOME created by Blackymas - https://github.com/Blackymas/NSPanel_HA_Blueprint  #####
##### ESPHOME CORE - Base                                                                       #####
##### PLEASE only make changes if it is necessary and also the required knowledge is available. #####
##### For normal use with the Blueprint, no changes are necessary.                              #####
#####################################################################################################

---
substitutions:
  ##############################
  ## Change only in your      ##
  ## local yaml substitutions ##
  ##############################
  BOOT_STEP_BASE: '0'
  device_name: nspanel
  friendly_name: ${device_name}
  GPIO_PSRAM_CLK_PIN: '5'
  GPIO_PSRAM_CS_PIN: '18'
  name: ${device_name}
  ota_password: ${wifi_password}
  project_tag: nspanel_ha_blueprint
  TAG_BASE: nspanel.base

button:
  - id: nspanel_factory_reset  # Factory Reset button - Used to clean values from flash
    name: Factory reset
    platform: factory_reset
    internal: false
    disabled_by_default: true
    icon: mdi:restart-alert

  - id: restart_nspanel  # Reboot ESP32
    name: Restart
    platform: restart

esp32:
  board: esp32dev
  framework:
    type: esp-idf

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  comment: NSPanel HA Blueprint
  project:
    name: Blackymas.NSPanel_HA_Blueprint
    version: bare
  platformio_options:
    build_flags:
      # - -Wno-missing-field-initializers
      - -D NSPANEL_HA_BLUEPRINT_BASE
  min_version: 2025.8.0

external_components:
  - source:
      type: git
      url: https://github.com/Blackymas/NSPanel_HA_Blueprint
      ref: v${version}
    refresh: 300s
    components:
      - nspanel_ha_blueprint

factory_reset:
  resets_required: 5
  max_delay: 60s

interval:
  - interval: 89s  # Intentionally a prime to reduce the occurences of this happening together with the time update
    startup_delay: 17s
    then:
      - script.execute: watchdog

logger:

nspanel_ha_blueprint:  # Adds custom library for NSPanel HA Blueprint project
  disable_bootloader_logs: false

ota:
  - id: ota_std
    platform: esphome
    password: ${ota_password}
    on_begin:
      then:
        - lambda: set_system_flag(NSPanelFlag::OTA_IN_PROGRESS);
        - script.execute: stop_all

safe_mode:

script:
  - id: dump_config
    mode: restart
    then:
      - delay: 10s

  - id: stop_all
    mode: restart
    then:
      - script.stop: dump_config
      - script.stop: watchdog

  - id: watchdog
    mode: restart
    then:
      - lambda: |-
          ESP_LOGI("${TAG_BASE}", "The watchdog is starting a round");
...
