#####################################################################################################
##### NSPANEL ESPHOME created by Blackymas - https://github.com/Blackymas/NSPanel_HA_Blueprint  #####
##### ESPHome Add-on for Climate control - Cool                                                 #####
##### PLEASE only make changes if it is necessary and also the required knowledge is available. #####
##### For normal use with the Blueprint, no changes are necessary.                              #####
#####################################################################################################
##### ATTENTION: This will add climate elements to the core system and requires the core part.  #####
#####################################################################################################
---
substitutions:
  ##############################
  ## Change only in your      ##
  ## local yaml substitutions ##
  ##############################
  ### Local thermostat defaults ###
  temp_min: "15"

  ##### DO NOT CHANGE THIS #####
  addon_climate_cool: "true"
  ##############################

esphome:
  platformio_options:
    build_flags:
      - -D NSPANEL_HA_BLUEPRINT_ADDON_CLIMATE_COOL

climate:
  - id: !extend thermostat_embedded
    min_cooling_off_time: ${min_off_time}s
    min_cooling_run_time: ${min_run_time}s
    cool_deadband: ${cool_deadband} ${temp_units}
    cool_overrun: ${cool_overrun} ${temp_units}
    cool_action:
      - switch.turn_on: relay_${cooler_relay}
    idle_action:
      - switch.turn_off: relay_${cooler_relay}
    preset:
      - name: "Off"
        default_target_temperature_high: ${target_high} ${temp_units}
        mode: "off"
      - name: Home
        default_target_temperature_high: ${target_high} ${temp_units}
        mode: "cool"

packages:
  climate_base_package: !include nspanel_esphome_addon_climate_base.yaml
...
