#####################################################################################################
##### NSPANEL ESPHOME created by Blackymas - https://github.com/Blackymas/NSPanel_HA_Blueprint  #####
##### ESPHOME - Page climate                                                                    #####
##### PLEASE only make changes if it is necessary and also the required knowledge is available. #####
##### For normal use with the Blueprint, no changes are necessary.                              #####
#####################################################################################################
---
substitutions:
  BOOT_STEP_PAGE_CLIMATE: '12'
  PAGE_CLIMATE_ID: '7'
  TAG_PAGE_CLIMATE: nspanel.page.climate

esphome:
  platformio_options:
    build_flags:
      - -D NSPANEL_HA_BLUEPRINT_PAGE_CLIMATE

script:
  - id: !extend event_from_display  # Defined by nspanel_esphome_core_hw_display.yaml
    then:
      - if:
          condition:
            - lambda: return page == "climate";
          then:
            - lambda: |-
                const std::string key = json["key"];
                const uint8_t embedded = json["embedded"];
                const std::string value = json["value"];
                change_climate_state->execute(embedded == 1, key.c_str(), value.c_str());

  - id: !extend page_change
    then:
      - if:
          condition:
            - lambda: return new_page_id == ${PAGE_CLIMATE_ID};
          then:
            - script.execute: page_climate

  - id: page_climate
    mode: single
    then:  # There's nothing here so far

...
