#####################################################################################################
##### NSPANEL ESPHOME created by Blackymas - https://github.com/Blackymas/NSPanel_HA_Blueprint  #####
##### ESPHOME - Page keyb_num                                                                   #####
##### PLEASE only make changes if it is necessary and also the required knowledge is available. #####
##### For normal use with the Blueprint, no changes are necessary.                              #####
#####################################################################################################
---
substitutions:
  BOOT_STEP_PAGE_KEYBOARD_NUM: 18
  PAGE_KEYB_NUM_ID: 24
  TAG_PAGE_KEYB_NUM: nspanel.page.keyb_num

esphome:
  platformio_options:
    build_flags:
      - -D NSPANEL_HA_BLUEPRINT_PAGE_KEYB_NUM

script:
  - id: !extend event_from_display
    then:
      - lambda: |-
          if (params[0] == "keyb_num") {
            // CSV Format: keyb_num,<base_domain>,<key>,<pin>
            // params[0]=page, params[1]=base_domain, params[2]=key, params[3]=pin

            if (params_count != 4) {
              ESP_LOGW("${TAG_PAGE_KEYB_NUM}", "Bad params");
              return;
            }

            const std::string& base_domain = params[1];
            const std::string& key = params[2];
            const std::string& pin = params[3];

            ESP_LOGV("${TAG_PAGE_KEYB_NUM}", "base_domain=%s, key=%s", base_domain.c_str(), key.c_str());

            if (base_domain == "alarm") {
              ESP_LOGV("${TAG_PAGE_KEYB_NUM}", "Executing alarm action");

              alarm_control_panel_action->execute(detailed_entity->state.c_str(),
                                                  key.c_str(), "number", pin.c_str());
            }

            ESP_LOGV("${TAG_PAGE_KEYB_NUM}", "Navigating to: %s",
                      base_domain.empty() ? "home" : base_domain.c_str());

            goto_page->execute(base_domain.empty() ? ${PAGE_HOME_ID} : get_page_id(base_domain.c_str()));
          }  // endif params[0] == "keyb_num"

  - id: !extend page_change
    then:
      - lambda: if (new_page_id == ${PAGE_KEYB_NUM_ID}) page_keyb_num->execute();

  - id: page_keyb_num
    mode: single
    then:  # There's nothing here so far

  - id: !extend stop_page_constructors
    then:
      - lambda: page_keyb_num->stop();
...
