#####################################################################################################
##### NSPANEL ESPHOME created by Blackymas - https://github.com/Blackymas/NSPanel_HA_Blueprint  #####
##### TFT Upload engine                                                                         #####
##### PLEASE only make changes if it is necessary and also the required knowledge is available. #####
##### For normal use with the Blueprint, no changes are necessary.                              #####
#####################################################################################################
##### ATTENTION: This will add advanced elements to the core system and requires the core part. #####
#####################################################################################################
---
substitutions:
  ################## Defaults ##################
  # Just in case user forgets to set something #
  nextion_update_base_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/"
  nextion_update_url: "${nextion_update_base_url}/main/hmi/nspanel_blank.tft"
  ##############################################
  BOOT_STEP_UPLOAD_TFT: '31'
  TAG_UPLOAD_TFT: nspanel_ha_blueprint.upload_tft

# yamllint disable rule:comments-indentation
api:
  actions:
    ##### TFT File Update action: `upload_tft`
      # Updates the panel's TFT file remotely from a specified URL or the default location,
      # requiring the "Upload TFT" add-on.
      # Usage: Essential for applying custom TFT designs or updates,
      # especially when direct repository access is unavailable.
      #
      # Parameters:
      # - `url` (string): URL for the TFT file. If "default" or empty,
      # uses the URL from "Update TFT - Display Model" in Home Assistant settings.
      #
      # Example:
      # action: esphome.<your_panel_name>_upload_tft
      # data:
      #   url: "http://homeassistant.local:8123/local/custom_tft_file.tft"  # Custom or default URL
      #
      # [!NOTE]
      # Utilize "default" to automatically use the URL associated with
      # the display model set in Home Assistant.
      #
      # [!ATTENTION]
      # Requires the "Upload TFT" add-on for functionality.
      # yamllint disable-line rule:indentation
      - action: upload_tft
        variables:
          url: string
        then:
          - lambda: |-
              std::string clean_url = url;
              // Convert to lowercase
              std::transform(clean_url.begin(), clean_url.end(), clean_url.begin(),
                            [](unsigned char c){ return std::tolower(c); });
              // Trim trailing spaces
              auto endPos = clean_url.find_last_not_of(" \t");
              if (std::string::npos != endPos) clean_url = clean_url.substr(0, endPos + 1);
              if (clean_url.empty() or clean_url == "default")
                url = construct_tft_url("v${version}", tft_file_model->state, "${nextion_update_url}",
                                        "${nextion_update_base_url}");
              upload_tft->execute(url.c_str());
# yamllint enable rule:comments-indentation

button:
  ##### UPDATE TFT DISPLAY #####
  - id: tft_update
    name: Update TFT display
    platform: template
    icon: mdi:file-sync
    entity_category: config
    on_press:
      then:
        - lambda: |-
            upload_tft->execute(construct_tft_url("v${version}", tft_file_model->state, "${nextion_update_url}",
                                                  "${nextion_update_base_url}").c_str());

display:
  - id: !extend disp1
    tft_url: ${nextion_update_url}
    exit_reparse_on_start: true

esphome:
  platformio_options:
    build_flags:
      - -D NSPANEL_HA_BLUEPRINT_STANDARD_UPLOAD_TFT

globals:
  - id: tft_upload_attempt
    type: uint8_t
    restore_value: false
    initial_value: '0'

  - id: tft_upload_result
    type: bool
    restore_value: false
    initial_value: 'false'

script:
  - id: !extend boot_package_register
    then:
      - lambda: boot_package_register_add->execute(${BOOT_STEP_UPLOAD_TFT}, "UPLOAD_TFT", "Upload TFT");

  - id: !extend boot_sequence
    then:
      - script.execute: select_tft_file_model

  - id: !extend dump_config
    then:
      - lambda: |-
          ESP_LOGCONFIG("${TAG_UPLOAD_TFT}", "Add-on Upload TFT:");
          ESP_LOGCONFIG("${TAG_UPLOAD_TFT}", "  File model: %s", tft_file_model->state.c_str());
          ESP_LOGCONFIG("${TAG_UPLOAD_TFT}", "  Valid TFT:  %s",
                          YESNO((id(display_mode) > 0 and id(display_mode) < 4)));

  - id: !extend check_versions
    then:
      - if:
          condition:
            - switch.is_on: tft_update_automatically
          then:
            - wait_until:
                condition:
                  - lambda: return compare_versions(version_tft->state.c_str(), "${version}");
                timeout: 60s
            - lambda: |-
                if (tft_update_automatically->state and
                    (not compare_versions(version_tft->state.c_str(), "${version}")) and
                    tft_file_model->state != "NSPanel Blank") {
                  ESP_LOGI("${TAG_UPLOAD_TFT}", "Automatically updating TFT");
                  upload_tft->execute(construct_tft_url("v${version}", tft_file_model->state, "${nextion_update_url}",
                                                        "${nextion_update_base_url}").c_str());
                }

  - id: !extend dump_config_packages  # Defined by nspanel_esphome_core_base.yaml
    then:
      - lambda: |-
          ESP_LOGCONFIG("${TAG_UPLOAD_TFT}", "  - Add-on - Upload TFT");

  - id: nextion_status
    mode: restart
    then:
      - lambda: |-
          ESP_LOGD("${TAG_UPLOAD_TFT}", "Nextion status:");
          ESP_LOGD("${TAG_UPLOAD_TFT}", "  Is detected: %s", YESNO(disp1->is_detected()));
          ESP_LOGD("${TAG_UPLOAD_TFT}", "  Is setup:    %s", YESNO(disp1->is_setup()));
          ESP_LOGD("${TAG_UPLOAD_TFT}", "  Queue size:  %d", disp1->queue_size());

  - id: nextion_upload
    mode: single
    parameters:
      baud_rate: uint32_t
    then:
      - logger.log: Waiting for empty UART and Nextion queues
      - wait_until:
          condition:
            - lambda: return (disp1->queue_size() < 1);
            - lambda: return (tf_uart->available() < 1);
          timeout: 10s
      - delay: 2s
      - logger.log: Starting TFT upload
      - lambda: |-
          ESP_LOGI("${TAG_UPLOAD_TFT}", "Starting TFT upload");
          id(tft_upload_result) = disp1->upload_tft(baud_rate, !disp1->is_setup());

  - id: open_upload_dialog
    mode: restart
    then:
      - lambda: |-
          if (current_page_id != ${PAGE_ID_BOOT}) {
            ESP_LOGD("${TAG_UPLOAD_TFT}", "Showing upload dialog page");
            goto_page_id->execute(${PAGE_ID_BOOT}, true);
          }
      - wait_until:
          condition:
            - lambda: return (current_page_id == ${PAGE_ID_BOOT});
          timeout: 2s
      - lambda: |-
          if (current_page_id == ${PAGE_ID_BOOT})
            disp1->set_component_text("initializing", "Uploading TFT...");

  - id: report_upload_progress
    mode: restart
    parameters:
      message: string
    then:
      - lambda: |-
          ESP_LOGI("${TAG_UPLOAD_TFT}", message.c_str());
          disp1->set_backlight_brightness(1);
      - if:
          condition:
            - lambda: return (id(display_mode) > 0 and id(display_mode) < 4);
          then:
            - lambda: |-
                if (current_page_id != ${PAGE_ID_BOOT})
                  open_upload_dialog->execute();
            - wait_until:
                condition:
                  - lambda: return (current_page_id == ${PAGE_ID_BOOT});
                timeout: 2s
            - lambda: |-
                page_boot_log->execute("TFT", message.c_str());

  - id: select_tft_file_model
    mode: restart
    then:
      - wait_until:
          condition:
            - lambda: return id(display_mode) > 0;
          timeout: 120s
      - lambda: |-
          ESP_LOGI("${TAG_UPLOAD_TFT}", "Display mode: %i", id(display_mode));
          if (id(display_mode) <= 0 or id(display_mode) >= 4)
            ESP_LOGE("${TAG_UPLOAD_TFT}", "Invalid TFT");
      - wait_until:
          condition:
            - lambda: return not isnan(id(display_charset));
      - lambda: |-
          std::string PanelModel = getNSPanelText(int(id(display_mode)), int(id(display_charset)));
          if (!PanelModel.empty() and tft_file_model->state != PanelModel)
            tft_file_model->publish_state(PanelModel);

  - id: !extend stop_all
    then:
      - lambda: |-
          nextion_status->stop();
          select_tft_file_model->stop();

  - id: upload_tft
    mode: single
    parameters:
      url: string
    then:
      # Make sure the screen is ON
      - if:
          condition:
            - switch.is_off: screen_power
          then:
            - switch.turn_on: screen_power
            - delay: 5s
      - script.execute: open_upload_dialog
      - script.wait: open_upload_dialog
      - wait_until:
          condition:
            - lambda: return (current_page_id == ${PAGE_ID_BOOT});
          timeout: 2s
      - script.execute:
          id: report_upload_progress
          message: "Set Nextion unavailable for blueprint calls"
      - script.wait: report_upload_progress
      - lambda: |-
          nextion_init->publish_state(false);
          report_upload_progress->execute("Preparing for upload...");
      - script.wait: report_upload_progress
      - script.execute: nextion_status
      # Then start the upload
      - lambda: |-
          // The upload process starts here
          ESP_LOGD("${TAG_UPLOAD_TFT}", "Starting the upload script");
          ESP_LOGD("${TAG_UPLOAD_TFT}", "  Valid TFT:  %s", YESNO((id(display_mode) > 0 and id(display_mode) < 4)));
          ESP_LOGD("${TAG_UPLOAD_TFT}", "  Baud rate:  %" PRIu32 " bps", tf_uart->get_baud_rate());
          ESP_LOGD("${TAG_UPLOAD_TFT}", "  Upload URL: %s", url.c_str());
          disp1->set_tft_url(url.c_str());

          // #ifdef USE_IMPROV
          // ESP_LOGD("${TAG_UPLOAD_TFT}", "Stop Improv BLE");
          // ble_improv->dump_config();
          // ble_improv->stop();
          // ble_improv->dump_config();
          // #endif
          // #ifdef USE_CAPTIVE_PORTAL
          // ESP_LOGD("${TAG_UPLOAD_TFT}", "Stop Captive Portal");
          // ap_captive_portal->dump_config();
          // ap_captive_portal->end();
          // ap_captive_portal->dump_config();
          // #endif
          #ifdef USE_ESP32_BLE_CLIENT
          ble_tracker->dump_config();
          ESP_LOGD("${TAG_UPLOAD_TFT}", "Disable BLE");
          bool ble_proxy_active_mode = false;
          #ifdef USE_BLUETOOTH_PROXY
          ble_proxy_active_mode = ble_proxy->has_active();
          ESP_LOGD("${TAG_UPLOAD_TFT}", "  Bluetooth proxy: %s", ble_proxy_active_mode ? "Active" : "Passive");
          if (ble_proxy_active_mode) {
            ESP_LOGD("${TAG_UPLOAD_TFT}", "    BT proxy set passive mode...");
            ble_proxy->set_active(false);
            delay(250);
            App.feed_wdt();
          }
          #endif  // USE_BLUETOOTH_PROXY
          ESP_LOGD("${TAG_UPLOAD_TFT}", "  Stopping BLE Tracker scan...");
          ble_tracker->stop_scan();
          delay(250);
          App.feed_wdt();
          ESP_LOGD("${TAG_UPLOAD_TFT}", "  Disabling BLE Tracker scan...");
          ble_tracker->set_scan_active(false);
          delay(250);
          App.feed_wdt();
          if (!ble_proxy_active_mode and ble_tracker->get_parent() != nullptr) {
            ESP_LOGD("${TAG_UPLOAD_TFT}", "  Disabling BLE...");
            delay(250);
            App.feed_wdt();
            ble_component->disable();
            delay(250);
            App.feed_wdt();
          }
          ble_tracker->dump_config();
          delay(250);
          App.feed_wdt();
          #endif  // USE_ESP32_BLE_CLIENT
          if ((id(display_mode) > 0 and id(display_mode) < 4) and
              current_page_id != ${PAGE_ID_BOOT})
            goto_page_id->execute(${PAGE_ID_BOOT}, true);
      - delay: 2s
      - script.execute: open_upload_dialog
      - script.wait: open_upload_dialog
      - wait_until:
          condition:
            - lambda: return (current_page_id == ${PAGE_ID_BOOT});
          timeout: 2s
      - script.execute:
          id: report_upload_progress
          message: "Stopping other scripts"
      - script.wait: report_upload_progress
      - script.execute: stop_all
      - script.wait: stop_all
      - wait_until:
          condition:
            - lambda: return (id(display_mode) > 0 and id(display_mode) < 4);
          timeout: 1s

      ### Attempt twice at the current baud rate
      - script.execute:
          id: upload_tft_sequence_attempt
          baud_rate: !lambda return tf_uart->get_baud_rate();
      - script.wait: upload_tft_sequence_attempt

      ### Attempt twice at the Nextion's default baud rate (115200bps)
      - if:
          condition:
            - lambda: return (tf_uart->get_baud_rate() != 115200);
          then:
            - script.execute:
                id: upload_tft_sequence_attempt
                baud_rate: 115200
            - script.wait: upload_tft_sequence_attempt

      ### Restart Nextion and attempt twice again at default baud rate (115200bps)
      - script.execute:
          id: report_upload_progress
          message: "Restarting Nextion display"
      - script.wait: report_upload_progress
      - wait_until:
          condition:
            - lambda: return (id(display_mode) > 0 and id(display_mode) < 4);
          timeout: 3s
      - switch.turn_off: screen_power
      - delay: 2s
      - switch.turn_on: screen_power
      - delay: 5s
      - script.execute:
          id: upload_tft_sequence_attempt
          baud_rate: 115200
      - script.wait: upload_tft_sequence_attempt

      ### All tries failed ###
      - script.execute:
          id: report_upload_progress
          message: "TFT upload failed"
      - script.wait: report_upload_progress
      - wait_until:
          condition:
            - lambda: return (id(display_mode) > 0 and id(display_mode) < 4);
          timeout: 5s
      - script.execute:
          id: report_upload_progress
          message: "Turn-off Nextion, restart ESPHome"
      - script.wait: report_upload_progress
      - wait_until:
          condition:
            - lambda: return (id(display_mode) > 0 and id(display_mode) < 4);
          timeout: 5s
      - switch.turn_off: screen_power
      - delay: 2s
      # Restart ESPHome
      - lambda: App.safe_reboot();

      ### This code should never run
      - delay: 2s
      - lambda: |-
          screen_power->turn_on();
          ESP_LOGE("${TAG_UPLOAD_TFT}", "TFT upload failed");

  - id: upload_tft_sequence_attempt
    mode: single
    parameters:
      baud_rate: uint32_t
    then:
      - script.execute: nextion_status
      - script.wait: nextion_status
      - script.execute:
          id: report_upload_progress
          message: "Set baud rate"
      - script.wait: report_upload_progress
      - script.execute:
          id: set_baud_rate
          baud_rate: !lambda return baud_rate;
          definitive: false
      - script.wait: set_baud_rate
      - delay: 2s
      - repeat:
          count: 2
          then:
            # First attempt
            - script.execute:
                id: upload_tft_attempt
                baud_rate: !lambda return baud_rate;
            - script.wait: upload_tft_attempt
            - delay: 5s

  - id: upload_tft_attempt
    mode: single
    parameters:
      baud_rate: uint32_t
    then:
      - lambda: |-
          ESP_LOGD("${TAG_UPLOAD_TFT}", "Upload TFT");
          id(tft_upload_attempt)++;
          char update_msg[128];
          sprintf(update_msg, "Try #%d (%" PRIu32 "bps)", id(tft_upload_attempt), tf_uart->get_baud_rate());
          id(tft_upload_result) = false;
          report_upload_progress->execute(update_msg);
      - script.wait: report_upload_progress
      - wait_until:
          condition:
            - lambda: return (id(display_mode) > 0 and id(display_mode) < 4);
          timeout: 1s
      - script.execute:
          id: nextion_upload
          baud_rate: !lambda return baud_rate;
      - script.wait: nextion_upload
      - lambda: |-
          char update_msg[128];
          sprintf(update_msg, "Try #%d (%" PRIu32 "bps): %s", id(tft_upload_attempt),
                  tf_uart->get_baud_rate(), YESNO(id(tft_upload_result)));
          report_upload_progress->execute(update_msg);
      - script.wait: report_upload_progress
      - if:
          condition:
            - lambda: return id(tft_upload_result);
          then:
            - delay: 5s
            - lambda: App.safe_reboot();

select:
  - id: tft_file_model
    name: Update TFT display - Model
    platform: template
    options:
      - "NSPanel Blank"
      - "NSPanel EU"
      - "NSPanel US"
      - "NSPanel US Landscape"
      - "NSPanel EU (CJK languages)"
      - "NSPanel US (CJK languages)"
      - "NSPanel US Landscape (CJK languages)"
      - "Use nextion_update_url"
    initial_option: "NSPanel EU"
    optimistic: true
    restore_value: true
    internal: false
    entity_category: config
    disabled_by_default: false
    icon: mdi:file-sync

switch:
  - id: tft_update_automatically
    name: Update TFT automatically
    platform: template
    icon: mdi:file-sync
    entity_category: config
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      then:
        - script.execute: check_versions
...
